# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alerta', models.IntegerField()),
                ('starting_alert', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_alert', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtentionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atention', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=200)),
                ('sounds', models.CharField(max_length=200)),
                ('print_promosions', models.BooleanField()),
                ('aleatory_promosion', models.BooleanField()),
                ('nombre_agencia', models.CharField(max_length=50)),
                ('cant_espera', models.IntegerField()),
                ('email_destino', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promosions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promosion', models.IntegerField()),
                ('promosion_message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_register', models.IntegerField()),
                ('atention_number', models.IntegerField()),
                ('start_atention', models.DateTimeField(default=django.utils.timezone.now)),
                ('observations', models.TextField()),
                ('finish_atention', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SellPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sellplace', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('people_attended', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.IntegerField()),
                ('sucursal_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
