# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0003_auto_20170507_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialAttention',
            fields=[
                ('id_initial_attention', models.AutoField(primary_key=True, serialize=False)),
                ('attention_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attentiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attentiontype',
            name='id_attention',
        ),
        migrations.AddField(
            model_name='attentiontype',
            name='id_attention_type',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registers',
            name='attention_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GE.AttentionType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registers',
            name='attention_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GE.InitialAttention'),
        ),
    ]
