# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0008_registers_priority_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='finish_total_attention',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
