# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0011_auto_20170608_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionesEstandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencia', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=200)),
                ('sounds', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='cant_espera',
            new_name='generar_alarma_con_cantidad',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='aleatory_promotion',
            new_name='imprimir_promocion',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='print_promotions',
            new_name='promocion_aleatoria',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='color',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='images',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='nombre_agencia',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='sounds',
        ),
    ]
