# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0018_auto_20170705_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='tiempo_espera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
