# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0019_registers_tiempo_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='observations',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
