# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0021_auto_20170706_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_selected',
            field=models.BooleanField(default=False),
        ),
    ]
