# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0023_auto_20170724_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='duracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registers',
            name='duracion_atencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registers',
            name='tiempo_espera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
