# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0027_auto_20180327_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='id_alerta',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attentiontype',
            name='id_attention_type',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='initialattention',
            name='id_initial_attention',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='promociones_visualizador',
            name='id_promociones_visualizador',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id_promotion',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registers',
            name='id_register',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sellplace',
            name='id_sellplace',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
