# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0004_auto_20170516_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialattention',
            name='attention_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GE.AttentionType'),
            preserve_default=False,
        ),
    ]
