# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0012_auto_20170608_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='pin',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='GE.Persona'),
            preserve_default=False,
        ),
    ]
