# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0013_registers_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
