# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0016_auto_20170617_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='sonido_totem',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registers',
            name='duracion_atencion',
            field=models.IntegerField(default=0),
        ),
    ]
