# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0022_promotion_promotion_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='email',
        ),
        migrations.AddField(
            model_name='configuration',
            name='visualizador_standard',
            field=models.BooleanField(default=False),
        ),
    ]
