# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0024_auto_20170803_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones_visualizador',
            fields=[
                ('id_promociones_visualizador', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_promocion_visualizador', models.CharField(max_length=100)),
            ],
        ),
    ]
