# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0026_auto_20170913_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='tipo_sonido_totem',
            field=models.CharField(default='Bells', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='tipo_sonido_visualizador',
            field=models.CharField(default='Bells', max_length=100),
            preserve_default=False,
        ),
    ]
